FROM node:20-alpine

WORKDIR /app

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY . .

RUN pnpm build

ENV PORT=3010
ENV NEXT_TELEMETRY_DISABLED=1

EXPOSE 3010

CMD ["pnpm", "start"]
